---

- block:
    - name: install epel-release (CentOS)
      yum:
        name: epel-release
        state: present
        update_cache: yes

    - name: install nginx
      package:
        name: nginx
        state: present
        update_cache: yes
  tags:
    - install
